### ISSUE TITLE
Mixed Content: The page at 'https://teleop.xyz/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://0.0.0.0:9090/'. This request has been blocked; this endpoint must be available over WSS.

### ISSUE THREAD

**Issue by awesomebytes** [datapartyjs/teleop-xyz#1]
Hello,

Thanks for sharing this work! I was gonna give it a quick try and, for now, I'm unable to make it work.

I tried:

* Run a roscore
* Play rosbag in a loop
* Launch rosbridge (`roslaunch rosbridge_server rosbridge_websocket.launch` in ROS melodic).
* Copy-paste the default rosbridge websocket url `ws://0.0.0.0:9090`
* Choose the default `/opt/ros/melodic/share/rviz/default.rviz` rviz file
* Click Connect.

I got a red dot saying 'Error' on the top right, and the chromium developer console shows the following error:
![Screenshot from 2021-10-25 11-15-49](https://user-images.githubusercontent.com/1721716/138618635-7f28fe81-81e6-4f02-9263-47119aa43df0.png)
(In text:
```
roslib.js:3258 Mixed Content: The page at 'https://teleop.xyz/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://0.0.0.0:9090/'. This request has been blocked; this endpoint must be available over WSS.
Ros.connect @ roslib.js:3258
(index):98 error DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Ros.connect (https://teleop.xyz/static/js/roslib.js:3258:18)
    at new Ros (https://teleop.xyz/static/js/roslib.js:3236:10)
    at eval (webpack-internal:///138:23:18)
    at new Promise (<anonymous>)
    at TeleOp.connectRos (webpack-internal:///138:20:12)
    at TeleOp.start (webpack-internal:///138:49:16)
    at HTMLFormElement.startConnection (https://teleop.xyz/:95:15)
```)

On firefox the error is different, but it's probably the same issue:
![Screenshot from 2021-10-25 11-21-02](https://user-images.githubusercontent.com/1721716/138618689-0e71e18d-1f59-446a-a600-55266535f2dc.png)
`error DOMException: The operation is insecure.`

**Comment by awesomebytes** [comment]
I see that if I clone the repository and open index.html I can connect (green dot), however I haven't been able to visualize any data (tried some full-fledged complex Rviz configs and also a simple one with just a pointcloud and one with just an Image).
